// engine/src/apps/socialShims/tiktok/tiktokSign.ts -- SUB-9, a full port of
// backend/apps/tiktok_mcp_shim/tiktok_sign.py.
//
// msToken is borrowed from the user's session cookies and appended to the query, which some read
// endpoints accept. X-Bogus / X-Gnarly is TikTok's rotating anti-automation signature, generated by
// obfuscated browser JS; we deliberately do NOT reproduce it here, because a stale or wrong
// signature is worse than none and TikTok changes it on a whim. When a call comes back
// signature-rejected, the shim says so and points at the browser agent, which signs naturally by
// being a real browser.

import { encodeQuery } from '../common/httpJson';
import { cookieValue } from '../common/sessionSource';
import { DEVICE_PARAMS, DOMAIN, MSTOKEN_COOKIE } from './tiktokEndpoints';

/** Build the query string with device params + the borrowed msToken. */
export async function signedQuery(params: Record<string, unknown>): Promise<string> {
  const q: Record<string, unknown> = { ...DEVICE_PARAMS };
  for (const [k, v] of Object.entries(params)) {
    if (v !== null && v !== undefined) q[k] = v;
  }
  const ms = await cookieValue(DOMAIN, MSTOKEN_COOKIE);
  if (ms) q.msToken = ms;
  // X-Bogus / X-Gnarly intentionally omitted; see module header.
  return encodeQuery(q);
}
